package financeiro;


/**
* financeiro/_contaCorrentePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from financeiro.idl
* Quinta-feira, 21 de Setembro de 2023 20h06min13s BRT
*/

public abstract class _contaCorrentePOA extends org.omg.PortableServer.Servant
 implements financeiro.contaCorrenteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("credita", new java.lang.Integer (0));
    _methods.put ("debita", new java.lang.Integer (1));
    _methods.put ("getSituacao", new java.lang.Integer (2));
    _methods.put ("setSituacao", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // financeiro/contaCorrente/credita
       {
         float valor = in.read_float ();
         boolean $result = false;
         $result = this.credita (valor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // financeiro/contaCorrente/debita
       {
         float valor = in.read_float ();
         boolean $result = false;
         $result = this.debita (valor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // financeiro/contaCorrente/getSituacao
       {
         String $result = null;
         $result = this.getSituacao ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 3:  // financeiro/contaCorrente/setSituacao
       {
         String msd = in.read_wstring ();
         boolean $result = false;
         $result = this.setSituacao (msd);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:financeiro/contaCorrente:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public contaCorrente _this() 
  {
    return contaCorrenteHelper.narrow(
    super._this_object());
  }

  public contaCorrente _this(org.omg.CORBA.ORB orb) 
  {
    return contaCorrenteHelper.narrow(
    super._this_object(orb));
  }


} // class _contaCorrentePOA
