package financeiro;

/**
* financeiro/contaCorrenteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from financeiro.idl
* Quinta-feira, 21 de Setembro de 2023 20h05min55s BRT
*/

public final class contaCorrenteHolder implements org.omg.CORBA.portable.Streamable
{
  public financeiro.contaCorrente value = null;

  public contaCorrenteHolder ()
  {
  }

  public contaCorrenteHolder (financeiro.contaCorrente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = financeiro.contaCorrenteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    financeiro.contaCorrenteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return financeiro.contaCorrenteHelper.type ();
  }

}
