package financeiro;


/**
* financeiro/contaCorrenteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from financeiro.idl
* Quinta-feira, 21 de Setembro de 2023 20h05min55s BRT
*/

abstract public class contaCorrenteHelper
{
  private static String  _id = "IDL:financeiro/contaCorrente:1.0";

  public static void insert (org.omg.CORBA.Any a, financeiro.contaCorrente that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static financeiro.contaCorrente extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (financeiro.contaCorrenteHelper.id (), "contaCorrente");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static financeiro.contaCorrente read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_contaCorrenteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, financeiro.contaCorrente value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static financeiro.contaCorrente narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof financeiro.contaCorrente)
      return (financeiro.contaCorrente)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      financeiro._contaCorrenteStub stub = new financeiro._contaCorrenteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static financeiro.contaCorrente unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof financeiro.contaCorrente)
      return (financeiro.contaCorrente)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      financeiro._contaCorrenteStub stub = new financeiro._contaCorrenteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
