package financeiro;


/**
* financeiro/contaCorrente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from financeiro.idl
* Quinta-feira, 21 de Setembro de 2023 20h05min55s BRT
*/

public interface contaCorrente extends contaCorrenteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface contaCorrente
